# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./include/Poco/Net/AcceptCertificateHandler.h \
    ./include/Poco/Net/CertificateHandlerFactory.h \
    ./include/Poco/Net/CertificateHandlerFactoryMgr.h \
    ./include/Poco/Net/ConsoleCertificateHandler.h \
    ./include/Poco/Net/Context.h \
    ./include/Poco/Net/InvalidCertificateHandler.h \
    ./include/Poco/Net/KeyConsoleHandler.h \
    ./include/Poco/Net/KeyFileHandler.h \
    ./include/Poco/Net/NetSSL.h \
    ./include/Poco/Net/PrivateKeyFactory.h \
    ./include/Poco/Net/PrivateKeyFactoryMgr.h \
    ./include/Poco/Net/PrivateKeyPassphraseHandler.h \
    ./include/Poco/Net/RejectCertificateHandler.h \
    ./include/Poco/Net/Session.h \
    ./include/Poco/Net/SSLException.h \
    ./include/Poco/Net/SSLManager.h \
    ./include/Poco/Net/Utility.h \
    ./include/Poco/Net/VerificationErrorArgs.h \
    ./include/Poco/Net/X509Certificate.h \
    ./include/Poco/Net/HTTPSClientSession.h \
    ./include/Poco/Net/HTTPSSessionInstantiator.h \
    ./include/Poco/Net/HTTPSStreamFactory.h \
    ./include/Poco/Net/SecureServerSocket.h \
    ./include/Poco/Net/SecureServerSocketImpl.h \
    ./include/Poco/Net/SecureSocketImpl.h \
    ./include/Poco/Net/SecureStreamSocket.h \
    ./include/Poco/Net/SecureStreamSocketImpl.h \
    ./include/Poco/Net/SecureSMTPClientSession.h
SOURCES += ./src/AcceptCertificateHandler.cpp \
    ./src/CertificateHandlerFactory.cpp \
    ./src/CertificateHandlerFactoryMgr.cpp \
    ./src/ConsoleCertificateHandler.cpp \
    ./src/Context.cpp \
    ./src/InvalidCertificateHandler.cpp \
    ./src/KeyConsoleHandler.cpp \
    ./src/KeyFileHandler.cpp \
    ./src/PrivateKeyFactory.cpp \
    ./src/PrivateKeyFactoryMgr.cpp \
    ./src/PrivateKeyPassphraseHandler.cpp \
    ./src/RejectCertificateHandler.cpp \
    ./src/Session.cpp \
    ./src/SSLException.cpp \
    ./src/SSLManager.cpp \
    ./src/Utility.cpp \
    ./src/VerificationErrorArgs.cpp \
    ./src/X509Certificate.cpp \
    ./src/HTTPSClientSession.cpp \
    ./src/HTTPSSessionInstantiator.cpp \
    ./src/HTTPSStreamFactory.cpp \
    ./src/SecureServerSocket.cpp \
    ./src/SecureServerSocketImpl.cpp \
    ./src/SecureSocketImpl.cpp \
    ./src/SecureStreamSocket.cpp \
    ./src/SecureStreamSocketImpl.cpp \
    ./src/SecureSMTPClientSession.cpp
