# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
#message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./include/Poco/Util/Application.h \
    ./include/Poco/Util/LoggingSubsystem.h \
    ./include/Poco/Util/ServerApplication.h \
    ./include/Poco/Util/Subsystem.h \
    ./include/Poco/Util/AbstractConfiguration.h \
    ./include/Poco/Util/ConfigurationMapper.h \
    ./include/Poco/Util/ConfigurationView.h \
    ./include/Poco/Util/FilesystemConfiguration.h \
    ./include/Poco/Util/IniFileConfiguration.h \
    ./include/Poco/Util/LayeredConfiguration.h \
    ./include/Poco/Util/LoggingConfigurator.h \
    ./include/Poco/Util/MapConfiguration.h \
    ./include/Poco/Util/PropertyFileConfiguration.h \
    ./include/Poco/Util/SystemConfiguration.h \
    ./include/Poco/Util/XMLConfiguration.h \
    ./include/Poco/Util/HelpFormatter.h \
    ./include/Poco/Util/IntValidator.h \
    ./include/Poco/Util/Option.h \
    ./include/Poco/Util/OptionCallback.h \
    ./include/Poco/Util/OptionException.h \
    ./include/Poco/Util/OptionProcessor.h \
    ./include/Poco/Util/OptionSet.h \
    ./include/Poco/Util/RegExpValidator.h \
    ./include/Poco/Util/Validator.h \
    ./include/Poco/Util/WinRegistryConfiguration.h \
    ./include/Poco/Util/WinRegistryKey.h \
    ./include/Poco/Util/WinService.h \
    ./include/Poco/Util/Util.h \
    ./include/Poco/Util/Timer.h \
    ./include/Poco/Util/TimerTask.h \
    ./include/Poco/Util/TimerTaskAdapter.h
SOURCES += ./src/Application.cpp \
    ./src/LoggingSubsystem.cpp \
    ./src/ServerApplication.cpp \
    ./src/Subsystem.cpp \
    ./src/AbstractConfiguration.cpp \
    ./src/ConfigurationMapper.cpp \
    ./src/ConfigurationView.cpp \
    ./src/FilesystemConfiguration.cpp \
    ./src/IniFileConfiguration.cpp \
    ./src/LayeredConfiguration.cpp \
    ./src/LoggingConfigurator.cpp \
    ./src/MapConfiguration.cpp \
    ./src/PropertyFileConfiguration.cpp \
    ./src/SystemConfiguration.cpp \
    ./src/XMLConfiguration.cpp \
    ./src/HelpFormatter.cpp \
    ./src/IntValidator.cpp \
    ./src/Option.cpp \
    ./src/OptionCallback.cpp \
    ./src/OptionException.cpp \
    ./src/OptionProcessor.cpp \
    ./src/OptionSet.cpp \
    ./src/RegExpValidator.cpp \
    ./src/Validator.cpp \
    ./src/WinRegistryConfiguration.cpp \
    ./src/WinRegistryKey.cpp \
    ./src/WinService.cpp \
    ./src/Timer.cpp \
    ./src/TimerTask.cpp
